### ISSUE TITLE
CHGRES error to process GFS data

### ISSUE THREAD

**Issue by uturuncoglu** [NOAA-EMC/UFS_UTILS#36]
The CHGRES packed with NCEPLIBS (github.com:NOAA-EMC/UFS_UTILS.git, @8b8db58, Nov 11 19:08:52 2019) triggers error when it tries to process GFS data. 

```
 - CALL FieldScatter FOR INPUT GRID TEMPERATURE.
 - FATAL ERROR: READING TEMPERATURE RECORD.
 - IOSTAT IS:          -31
MPT ERROR: Rank 0(g:0) received signal SIGSEGV(11).
        Process ID: 43767, Host: r12i0n32, Program: /glade/scratch/turuncu/ufs-mrweather-app-workflow/bld/chgres_cube.exe
        MPT Version: HPE MPT 2.19  02/23/19 05:30:09
```

and the error trace is 

```
MPT:     rc=<error reading variable: Cannot access memory at address 0x0>,
MPT:     .tmp.STRING.len_V$7=14336928)
MPT:     at /glade/work/turuncu/UFS/NCEP_LIBS_ALL/UFS_UTILS/sorc/chgres_cube.fd/utils.f90:11
MPT: #8  0x00000000004590fa in input_data::read_input_atm_gaussian_file (localpet=0)
MPT:     at /glade/work/turuncu/UFS/NCEP_LIBS_ALL/UFS_UTILS/sorc/chgres_cube.fd/input_data.F90:1254
MPT: #9  0x0000000000435a5f in input_data::read_input_atm_data (localpet=0)
MPT:     at /glade/work/turuncu/UFS/NCEP_LIBS_ALL/UFS_UTILS/sorc/chgres_cube.fd/input_data.F90:147
MPT: #10 0x000000000041092a in atmosphere::atmosphere_driver (localpet=0)
MPT:     at /glade/work/turuncu/UFS/NCEP_LIBS_ALL/UFS_UTILS/sorc/chgres_cube.fd/atmosphere.F90:145
MPT: #11 0x0000000000435839 in chgres ()
MPT:     at /glade/work/turuncu/UFS/NCEP_LIBS_ALL/UFS_UTILS/sorc/chgres_cube.fd/chgres.F90:78
```
The same data and the namelist can be processed with the external CHGRES installation used in the prototype system. This version has last commit from George Gayno on Fri Sep 6 10:29:16 2019 and hash is @947145c. 

I also test to install NCEP LIBS with Intel 18.0.5 and system provided NetCDF (4.7.1) but it does not help.

**Comment by uturuncoglu** [comment]
The top level hash for NCEPLIBS is e9131cc

**Comment by GeorgeGayno-NOAA** [comment]
Resolved.  There was no problem with the chgres code.  The problem was with the nemsio library.  For details see: https://github.com/ufs-community/ufs-mrweather-app/issues/6

Closing issue.
