### ISSUE TITLE
chgres_cube crashes with segmentation fault

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/UFS_UTILS#584]
chgres_cube segfaults in input_data.F90 (line 5495). Here's the backtrace:
```
[1]
[1] Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
[1]
[1] Backtrace for this error:
[1] #0  0x14afd2d1edfd in ???
[1] #1  0x14afd2d1e013 in ???
[1] #2  0x14afd1ffa3ff in ???
[1] #3  0x508800 in read_input_sfc_grib2_file
[1]     at /home/builder/simple-ufs/src/preproc/sorc/chgres_cube.fd/input_data.F90:5495
[1] #4  0x58b9b8 in __surface_MOD_surface_driver
[1]     at /home/builder/simple-ufs/src/preproc/sorc/chgres_cube.fd/surface.F90:189
[1] #5  0x4b9d87 in chgres
[1]     at /home/builder/simple-ufs/src/preproc/sorc/chgres_cube.fd/chgres.F90:108
[1] #6  0x4b71ac in main
[1]     at /home/builder/simple-ufs/src/preproc/sorc/chgres_cube.fd/chgres.F90:26
```
`slmsk_save` array is allocated only on task 0. It must be allocated on all tasks:

```diff
diff --git a/sorc/chgres_cube.fd/input_data.F90 b/sorc/chgres_cube.fd/input_data.F90
index e3f4b12..ecb65f4 100644
--- a/sorc/chgres_cube.fd/input_data.F90
+++ b/sorc/chgres_cube.fd/input_data.F90
@@ -4797,7 +4797,7 @@ else
    allocate(dummy2d_8(0,0))
    allocate(dummy2d_82(0,0))
    allocate(dummy2d(0,0))
-
+   allocate(slmsk_save(0,0))
  endif
 
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by GeorgeGayno-NOAA** [comment]
@DusanJovic-NOAA  Thanks.  Will take a look.

**Comment by GeorgeGayno-NOAA** [comment]
@DusanJovic-NOAA Which compiler were you using?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Which compiler were you using?

GNU.

**Comment by GeorgeGayno-NOAA** [comment]
@DusanJovic-NOAA Try my branch at 7c9cc6b

**Comment by DusanJovic-NOAA** [comment]
Works fine. Thanks.
